// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("API.Entities.Clip", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BroadcasterId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("broadcaster_id");

                    b.Property<string>("BroadcasterName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("broadcaster_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatorId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_id");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("creator_name");

                    b.Property<double>("Duration")
                        .HasMaxLength(120)
                        .HasColumnType("REAL")
                        .HasColumnName("duration");

                    b.Property<string>("EmbedUrl")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("embed_url");

                    b.Property<string>("GameId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<string>("GameName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("game_name");

                    b.Property<string>("Language")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<string>("VideoId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("video_id");

                    b.Property<int>("ViewCount")
                        .HasMaxLength(120)
                        .HasColumnType("INTEGER")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.ToTable("Clip");
                });

            modelBuilder.Entity("API.Entities.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BoxArtUrl")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("box_art_url");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
